// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiYGOhuj6OzSoYrN9PJblWWDrIcthfNBE',
    appId: '1:937871361250:web:0eb53bf5360ac9b4010abb',
    messagingSenderId: '937871361250',
    projectId: 'lumina-study-df770',
    authDomain: 'lumina-study-df770.firebaseapp.com',
    storageBucket: 'lumina-study-df770.firebasestorage.app',
    measurementId: 'G-PVXSL0MEHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgJ24Or12CSXH-aDHnOe-w0bNLTcaweAU',
    appId: '1:937871361250:android:8bfc4ff3df012033010abb',
    messagingSenderId: '937871361250',
    projectId: 'lumina-study-df770',
    storageBucket: 'lumina-study-df770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZsYnKznJB1gI9lML5VNZKvp4TvC1WxfE',
    appId: '1:937871361250:ios:07537d7e123e6b54010abb',
    messagingSenderId: '937871361250',
    projectId: 'lumina-study-df770',
    storageBucket: 'lumina-study-df770.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZsYnKznJB1gI9lML5VNZKvp4TvC1WxfE',
    appId: '1:937871361250:ios:07537d7e123e6b54010abb',
    messagingSenderId: '937871361250',
    projectId: 'lumina-study-df770',
    storageBucket: 'lumina-study-df770.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiYGOhuj6OzSoYrN9PJblWWDrIcthfNBE',
    appId: '1:937871361250:web:f37cc5e2323ebade010abb',
    messagingSenderId: '937871361250',
    projectId: 'lumina-study-df770',
    authDomain: 'lumina-study-df770.firebaseapp.com',
    storageBucket: 'lumina-study-df770.firebasestorage.app',
    measurementId: 'G-GS13MGDBEQ',
  );
}
